version: '3'

services:
  # App de Payload CMS
  payload:
    image: node:18-alpine # Volvemos a Node
    ports:
      - '3050:3050'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    # Usar pnpm para instalar e iniciar
    command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm dev"
    env_file:
      - .env

volumes:
  node_modules:
